# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['getAtl03_GUI.py'],
             pathex=['C:\\Users\\malonzo\\GLAM\\Python\\PhoREAL_GUI\\GUI_3.0'],
             binaries=[],
             datas=[('pho_image.ico', '.'),
			('phorealc.so', '.'),
			('closest_x64.dll', '.'),
			('geoid_egm2008.mat','.'),
			('geoid12b_alaska_latlon.mat','.'),
			('geoid12b_guam_latlon.mat','.'),
			('geoid12b_hawaii_latlon.mat','.'),
			('geoid12b_latlon.mat','.'),
			('geoid12b_puerto_rico_latlon.mat','.'),
			('geoid12b_samoa_latlon.mat','.'),
			('geoidFin2005N00_latlon.mat','.'),
			('geoidNZ_latlon.mat','.'),
			('Viewer_Online_blank.html','.'),
			('Viewer_blank.html','.')],
             hiddenimports=[],
			 hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='PhoReal_v3.0',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True , icon='pho_image.ico')
